### ISSUE TITLE
Runtime error on composer install

### ISSUE THREAD

**Issue by morgothx** [oscarricardosan/phpunitg-laravel-dashboard#1]
Hi, I run composer install and

RuntimeException]                                                                                                   
  Source path "/home/vagrant/Code/phpunitg-laravel/package" is not found for package oscarricardosan/phpunitg_laravel

I'm running on a ubuntu 16.04 box with apache and php 7.2

**Comment by oscarricardosan** [comment]
Hi, excuse me, for carelessness leave a package pointing to local. Corrected.

Execute  `git pull`   and `composer install` or re-download the project.

Any other inconsistency counts with me
oscarricardosan@gmail.com

**Comment by morgothx** [comment]
Thank you, i will try tonight
